### ISSUE TITLE
Make SCvx and GuSTO work in the jgcd branch

### ISSUE THREAD

**Issue by dmalyuta** [UW-ACL/SCPToolbox.jl#4]
Currently the SCvx and GuSTO algorithms are working only in the `master` and `csm` branches. As #3 mentioned, the `jgcd` branch does not have these solvers yet. This is due to using a more interesting back-end parser code to keep track of SCP subproblems as convex programming programs in conic form. The PTR algorithm was ported to use this back-end, while SCvx and GuSTO have not yet been.

Timeline to completion: the next 1-2 months.

**Comment by Zentrik** [comment]
Do you want me to open a pull request with my implementation of scvx for jgcd branch?

**Comment by dmalyuta** [comment]
SCvx and GuSTO now work very well in the `master` branch, and I'll not be pursuing making them work in the `jgcd` branch which is very stale at this point.
