### ISSUE TITLE
use toolbox in c++ programe

### ISSUE THREAD

**Issue by DingFeng9313** [UW-ACL/SCPToolbox.jl#5]
First of all, thanks for your great work, it helps me learning trajectory optimization.

Now I want to use this in a c++ program. I wonder where should I start.
I noticed the underdying solver of scp_traj_opt is ECOS solver which is a c library. But scp_tool_box also use JuMP. So if I want to solve a c++ trajectory optimization problem. Where should I start? Is it better to just rewrite SCP_TOOL_BOX in c++ or should I look for other trajectory optimization toolbox in C++?

**Comment by dmalyuta** [comment]
The SCP Toolbox was not designed with easy C++ integration in mind. Your best bet is to generate trajectories amd to store them as text files to be read in C++. You can also feasibly to a system call from C++ to run the toolbox on-demand from your C++ application, kind of like a client (C++) server (Julia) solution. But that won't be fast, if real-time is what you're after.
